//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject.Infrastructure.Framework.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleProject.Infrastructure.Framework.Globalization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível carimbar um registro sem usuário (userid == 0)..
        /// </summary>
        public static string CanStampRecordWithNoUser {
            get {
                return ResourceManager.GetString("CanStampRecordWithNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível realizar operações sobre valores de moedas diferentes..
        /// </summary>
        public static string InvalidMoneyOperationDifferentCurrencies {
            get {
                return ResourceManager.GetString("InvalidMoneyOperationDifferentCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo para {0} é {1} caracteres..
        /// </summary>
        public static string MaxLengthNotSatisfiedReason {
            get {
                return ResourceManager.GetString("MaxLengthNotSatisfiedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho mínimo para {0} é {1} caracteres..
        /// </summary>
        public static string MinLengthNotSatisfiedReason {
            get {
                return ResourceManager.GetString("MinLengthNotSatisfiedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preenchimento de {0} é requerido..
        /// </summary>
        public static string MustExistsSpecification {
            get {
                return ResourceManager.GetString("MustExistsSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; deve existir..
        /// </summary>
        public static string MustNotBeNullSpecification {
            get {
                return ResourceManager.GetString("MustNotBeNullSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; de &quot;{1}&quot; é requerido..
        /// </summary>
        public static string NullOrDefaultPropertySpecification {
            get {
                return ResourceManager.GetString("NullOrDefaultPropertySpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha antiga está incorreta..
        /// </summary>
        public static string OldPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("OldPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso..
        /// </summary>
        public static string PasswordChangeSuccessful {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a senha.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha expirou. É necessário realizar a troca da senha para prosseguir..
        /// </summary>
        public static string PasswordExpiredDescription {
            get {
                return ResourceManager.GetString("PasswordExpiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha expirada.
        /// </summary>
        public static string PasswordExpiredTitle {
            get {
                return ResourceManager.GetString("PasswordExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ser diferente das últimas {0} senhas utilizadas..
        /// </summary>
        public static string PasswordMustBeDiffThanLastPasswords {
            get {
                return ResourceManager.GetString("PasswordMustBeDiffThanLastPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos {0} caracteres..
        /// </summary>
        public static string PasswordMustHaveAtLeastChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos {0} número..
        /// </summary>
        public static string PasswordMustHaveAtLeastNumber {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos {0} caracter especial..
        /// </summary>
        public static string PasswordMustHaveAtLeastSpecialChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos {0} letra maiúscula..
        /// </summary>
        public static string PasswordMustHaveAtLeastUppercaseChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastUppercaseChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no mínimo 8 caracteres, incluindo maiúsculas, caracteres especiais e alfanuméricos, e deve ser diferente das últimas 20 senhas utilizadas..
        /// </summary>
        public static string PasswordPolicyDescription {
            get {
                return ResourceManager.GetString("PasswordPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação enviada com sucesso..
        /// </summary>
        public static string PasswordResetTokenGenerated {
            get {
                return ResourceManager.GetString("PasswordResetTokenGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preenchimento de {0} é requerido..
        /// </summary>
        public static string RequiredNotSatisfiedReason {
            get {
                return ResourceManager.GetString("RequiredNotSatisfiedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papel.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário &quot;{0}&quot; não pode ser removido. Se não desejar mais utilizá-lo, apenas desabilite-o..
        /// </summary>
        public static string SpecialUserCannotBeRemoved {
            get {
                return ResourceManager.GetString("SpecialUserCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail inválido..
        /// </summary>
        public static string ThereIsNoUserWithThisEmail {
            get {
                return ResourceManager.GetString("ThereIsNoUserWithThisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe {0} com o nome &quot;{1}&quot;..
        /// </summary>
        public static string ThereIsOtherEntityWithSameName {
            get {
                return ResourceManager.GetString("ThereIsOtherEntityWithSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe {0} com o valor &quot;{1}&quot;..
        /// </summary>
        public static string ThereIsOtherEntityWithSameValue {
            get {
                return ResourceManager.GetString("ThereIsOtherEntityWithSameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválida..
        /// </summary>
        public static string UrlNotSatisfiedReason {
            get {
                return ResourceManager.GetString("UrlNotSatisfiedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não pode ser alterada, pois o usuário não está habilitado..
        /// </summary>
        public static string UserDisabledCannotChangePassword {
            get {
                return ResourceManager.GetString("UserDisabledCannotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token para reset de senha expirado..
        /// </summary>
        public static string UserPasswordResetTokenExpired {
            get {
                return ResourceManager.GetString("UserPasswordResetTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário com id &quot;{0}&quot; não existe..
        /// </summary>
        public static string UserWithIdDoNotExists {
            get {
                return ResourceManager.GetString("UserWithIdDoNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
